#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWBMo37IsVyvy0aT8FMO7NiFPIxfrUCyp5BA4b4Pr69BahfFuTgHLzkmPz9N0DE7EAHgjTV0QSLAYHWrmJG/8H8K/x9kz9sIK03jySSib+hIpnMdtt4+rC6AiQI9lmYyXeaZPwAaZe+KOozNJvzutRd31vrFJ3VZUQ2rMgNC2x0SyF1kEle/zEwkNMW4E0ea07u6MXrv5aSGyFNakiqpxVO12MQE/UocgiloHurcWP4CSCygdjLre031LwQ80xIIbSslyYG/g8W6DVexOBMyJ5tbw+C0SETBb6d4pA1slrALybQOgD/DWaPtV2aiZJl5ch8GtdjqBtCc2JO9+uJzM3 rsa-key-20230411

packages:
 - git
 
runcmd:
  - useradd -m -U -d /var/puma puma
  - cd /var/puma
  - git clone -b monolith https://github.com/admiralissimus/reddit.git
  - cd reddit 
  - git checkout 2b9f78b3232d732bebb7de1a2d0e475aea90d73c
  - cp ./puma.service /etc/systemd/system/puma.service 
  - bundle install
  - chown root:root /etc/systemd/system/puma.service
  - systemctl start puma
  - systemctl enable puma
 